name: Deploy site to AWS EC2

on:
  # Uncomment these lines if you want to run on push or pull request events to the main branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-html-ec2:
    env:
      PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      HOSTNAME: ${{ vars.AWS_HOSTNAME }}
      USER_NAME: ${{ vars.AWS_USER_NAME }}
            
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          ls
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
            ls -l
            cd /var/www/html
            echo "Deployed on $(date)" > index.html
          EOF
