name: Deploy site to AWS EC2

on:
  # Uncomment these lines if you want to run on push or pull request events to the main branch
  push:
     branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-html-ec2:
    environment: Development
    runs-on: ubuntu-latest
    env:
        PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        HOSTNAME: ${{ vars.AWS_HOSTNAME }}
        USER_NAME: ${{ vars.AWS_USER_NAME }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create temp key
        run: |
          echo "$PRIVATE_KEY" > moongy-key.pem
          chmod 400 moongy-key.pem 

      - name: lista diretorios
        run: |
          ls
          ls wwwroot
        
      - name: publish wwwroot to EC2
        run: |                    
          cd wwwroot          
          scp -o StrictHostKeyChecking=no -i ../moongy-key.pempem -r . ${USER_NAME}@${HOSTNAME}:/var/www/html/do2/
      
      
